name: simple_dio_cache_interceptor
description: >
  A lightweight and easy-to-use Dio interceptor for caching GET requests in Flutter or Dart apps. 
  Ideal for simple use cases where response caching based on duration is needed.
version: 1.0.0
repository: https://github.com/gabbygreat/simple_dio_cache_interceptor.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1

dev_dependencies:
  http_mock_adapter: ^0.6.1
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
